=== vinhtnk/xml-project-hv/Demo/XMLProject/src/conf/xml-resources/jaxb/Users/users.xsd
<?xml version="1.0" encoding="UTF-8"?>

<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema"
    targetNamespace="http://xml.netbeans.org/schema/users"
    xmlns="http://xml.netbeans.org/schema/users"
    elementFormDefault="qualified">
    <xsd:element name="users">
        <xsd:complexType>
            <xsd:sequence>
                <xsd:element name="User" type="UserType" maxOccurs="unbounded"></xsd:element>
            </xsd:sequence>
        </xsd:complexType>
    </xsd:element>
    <xsd:complexType name="UserType">
        <xsd:sequence>
            <xsd:element name="UserId" type="xsd:positiveInteger"/>
            <xsd:element name="UserName" type="xsd:string"/>
            <xsd:element name="Email" type="xsd:string"/>
            <xsd:element name="FullName" type="xsd:string"/>
            <xsd:element name="Role" type="xsd:positiveInteger"/>
            <xsd:element name="Phone" type="xsd:string"/>
        </xsd:sequence>
        <xsd:attribute name="password" type="passwordtype"/>
    </xsd:complexType>
    <xsd:simpleType name="passwordtype">
        <xsd:restriction base="xsd:string">
            <xsd:pattern value="[A-Za-z0-9]{6,12}"/>
        </xsd:restriction>
    </xsd:simpleType>

</xsd:schema>

=== vinhtnk/xml-project-hv/Demo/XMLProject/src/java/xml/Users.xml
<?xml version="1.0" encoding="UTF-8"?>

<!--
    Document   : Users.xml
    Created on : June 6, 2013, 5:38 AM
    Author     : Quaikiet
    Description:
        Purpose of the document follows.
-->

<users  xmlns:xsi='http://www.w3.org/2001/XMLSchema-instance'
   xmlns='http://xml.netbeans.org/schema/users'
   xsi:schemaLocation='http://xml.netbeans.org/schema/users ../schema/users.xsd'>
    <User password="asd123456">
        <UserId>1</UserId>
        <UserName>asd</UserName>
        <Email>asd</Email>
        <FullName>asd</FullName>
        <Role>1</Role>
        <Phone>asdad</Phone>
    </User>
    <User password="zxc123456">
        <UserId>1</UserId>
        <UserName>asd</UserName>
        <Email>asd</Email>
        <FullName>asd</FullName>
        <Role>1</Role>
        <Phone>asdad</Phone>
    </User>
   
</users>
