=== vinhtnk/xml-project-hv/Demo/XMLProject/src/conf/xml-resources/jaxb/Games/games.xsd
<?xml version="1.0" encoding="UTF-8"?>

<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema"
    targetNamespace="http://xml.netbeans.org/schema/games"
    xmlns="http://xml.netbeans.org/schema/games"
    elementFormDefault="qualified">
    <xsd:element name="games">
        <xsd:complexType>
            <xsd:sequence>
                <xsd:element name="Game" type="GameType" maxOccurs="unbounded"/>
            </xsd:sequence>
        </xsd:complexType>
    </xsd:element>
    <xsd:complexType name="GameType">
        <xsd:sequence>
            <xsd:element name="GameId" type="xsd:positiveInteger"/>
            <xsd:element name="Name" type="xsd:string"/>
            <xsd:element name="Price" type="xsd:float"/>
            <xsd:element name="Pinboard" type="xsd:string"/>
            <xsd:element name="Description" type="xsd:string"/>
            <xsd:element name="Image_URL" type="xsd:string"/>
            <xsd:element name="CreatedDate" type="xsd:dateTime"/>
            <xsd:element name="GenreId" type="xsd:string"/>
        </xsd:sequence>
    </xsd:complexType>
    
    

</xsd:schema>

=== vinhtnk/xml-project-hv/Demo/XMLProject/src/java/xml/games.xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-stylesheet type="text/xsl" href="stylesheet/games.xsl"?>
<!--
    Document   : games.xml
    Created on : June 6, 2013, 6:45 AM
    Author     : Quaikiet
    Description:
        Purpose of the document follows.
-->

<games  xmlns:xsi='http://www.w3.org/2001/XMLSchema-instance'
   xmlns='http://xml.netbeans.org/schema/games'
   xsi:schemaLocation='http://xml.netbeans.org/schema/games games.xsd'>
    <Game>
        <GameId>1</GameId>
        <Name>Dota</Name>
        <Price>9.9</Price>
        <Pinboard>ASD</Pinboard>
        <Description>DSA</Description>
        <Image_URL>asdzc</Image_URL>
        <CreatedDate>2002-09-24T11:12:12</CreatedDate>
    </Game>

</games>
